services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=simple_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_SOURCE=postgres://postgres:mysecretpassword@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["./wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
